Repository developers-pantaneiros/game, pull requests merged in 2020-04, with the labels that each got.

#53 Implementar tradutor de libras
  README.md
  public/index.html
  src/App.vue
  src/assets/scss/components/_container.scss
  src/assets/scss/components/_wrapper-app.scss
  src/assets/scss/main.scss
  src/commons/components/PoundsTranslator.vue
Labels: feature

#55 Melhorias no layout da aplicação
  src/views/external/signup/Signup.vue
  src/views/external/signup/components/SignupActions.vue
  src/views/internal/student/class/ranking/ClassRanking.vue
Labels: layout

#61 Botão fechar no modal
  src/commons/components/Alert.vue
Labels: layout

#57 Botão de feedback da plataforma
  src/App.vue
  src/commons/components/Alert.vue
  src/commons/components/FeedbackAlert.vue
  src/commons/components/FeedbackButton.vue
Labels: feature

#52 Melhoria no botão de transcrição de textos
  src/App.vue
  src/assets/scss/base/_typography.scss
  src/assets/scss/base/_utilities.scss
  src/assets/scss/components/_audio-button.scss
  src/assets/scss/main.scss
  src/commons/components/Alert.vue
  src/commons/components/AudioButton.vue
  src/views/external/greetings/Greetings.vue
  src/views/external/greetings/components/GreetingsCarousel.vue
  src/views/external/reset/ResetPassword.vue
  src/views/external/signin/Signin.vue
  src/views/external/signup/Signup.vue
  src/views/internal/student/class/add/ClassAdd.vue
  src/views/internal/student/class/classroom/ClassRoom.vue
  src/views/internal/student/class/exercises/ClassExercises.vue
  src/views/internal/student/class/ranking/ClassRanking.vue
  src/views/internal/student/class/search/ClassSearch.vue
  src/views/internal/student/exercises/first/ExerciseFirst.vue
  src/views/internal/student/exercises/first/components/Feedback.vue
  src/views/internal/teacher/class/detail/ClassAdd.vue
  src/views/internal/teacher/class/detail/ClassView.vue
  src/views/internal/teacher/class/search/ClassSearch.vue
Labels: layout, refactoring, warning

#62 Melhoria na interface de visualização de dados da turma
  src/App.vue
  src/assets/scss/base/_utilities.scss
  src/assets/scss/components/_student-card.scss
  src/assets/scss/main.scss
  src/commons/components/AudioButton.vue
  src/views/internal/student/class/classroom/ClassRoom.vue
  src/views/internal/student/class/classroom/components/ClassRoomStudentCard.vue
Labels: layout, refactoring

#65 Botão para copiar código da turma
  package-lock.json
  package.json
  src/main.js
  src/views/internal/teacher/class/detail/ClassView.vue
Labels: feature, layout

#56 Melhoria no cálculo do score
  src/App.vue
  src/globals/router/routes/student.js
  src/views/internal/student/class/score/ClassScore.vue
  src/views/internal/student/exercises/first/ExerciseFirst.vue
Labels: layout, refactoring

#66 Alteracao nas descricoes dos botoes
  src/assets/scss/abstracts/_corrections.scss
  src/views/external/reset/components/ResetPasswordFormActions.vue
  src/views/external/signin/components/SigninActions.vue
  src/views/external/signup/components/SignupActions.vue
  src/views/internal/student/class/search/ClassSearch.vue
  src/views/internal/student/class/search/components/ClassSearchAction.vue
  src/views/internal/student/class/search/components/ClassSearchSignOut.vue
  src/views/internal/teacher/class/detail/ClassView.vue
  src/views/internal/teacher/class/search/ClassSearch.vue
  src/views/internal/teacher/class/search/components/ClassSearchAction.vue
  src/views/internal/teacher/class/search/components/ClassSearchSignOut.vue
Labels: layout, refactoring

#59 Padronização de parâmetros das rotas
  src/globals/router/routes/student.js
  src/globals/router/routes/teacher.js
  src/views/internal/student/class/add/AbstractClassAdd.vue
  src/views/internal/student/class/classroom/ClassRoom.vue
  src/views/internal/student/class/search/ClassSearch.vue
  src/views/internal/student/class/search/components/ClassSearchCard.vue
  src/views/internal/student/exercises/first/components/Feedback.vue
  src/views/internal/teacher/class/detail/ClassAdd.vue
  src/views/internal/teacher/class/detail/ClassView.vue
  src/views/internal/teacher/class/search/components/ClassSearchCard.vue
Labels: refactoring

#67 Persistência de dados no estado da aplicação
  package-lock.json
  src/App.vue
  src/commons/store/actions.js
  src/commons/store/mutations.js
  src/views/external/greetings/Greetings.vue
  src/views/internal/student/class/classroom/ClassRoom.vue
  src/views/internal/student/class/search/ClassSearch.vue
Labels: technical, warning

#69 Correção de alertas para funcionamento no iPhone
  src/commons/components/Alert.vue
  src/commons/components/FeedbackAlert.vue
Labels: bug

#70 Alterações no README.md
  README.md
Labels: layout

#63 Manter nome da turma nas telas da classe
  src/views/internal/student/class/classroom/ClassRoom.vue
  src/views/internal/student/class/commons/ClassName.vue
  src/views/internal/student/class/exercises/ClassExercises.vue
  src/views/internal/student/class/score/ClassScore.vue
Labels: layout, refactoring

#68 Correção na renderização das barras de progresso
  src/views/internal/student/class/score/ClassScore.vue
Labels: bug

#72 Ajuste na posição do badge com código da classe
  src/views/internal/teacher/class/detail/ClassView.vue
Labels: bug, layout

#71 Correção dos botões que estão ultrapassando o padding do container
  src/assets/scss/base/_utilities.scss
  src/views/external/reset/components/ResetPasswordFormActions.vue
  src/views/external/signin/components/SigninActions.vue
  src/views/external/signup/components/SignupActions.vue
  src/views/internal/student/class/add/ClassAddCodeReader.vue
  src/views/internal/student/class/add/components/ClassFormActions.vue
  src/views/internal/student/exercises/first/ExerciseFirst.vue
  src/views/internal/student/exercises/first/components/Feedback.vue
  src/views/internal/teacher/class/detail/ClassView.vue
  src/views/internal/teacher/class/detail/components/ClassFormActions.vue
Labels: bug

#73 Ajuste na inicialização de rotas da aplicação
  src/views/external/greetings/Greetings.vue
Labels: technical

#75 Refatoração | Desafio 1
  src/commons/components/Alert.vue
  src/commons/components/StateAlert.vue
  src/views/internal/student/exercises/first/ExerciseFirst.vue
  src/views/internal/student/exercises/first/components/Feedback.vue
  src/views/internal/student/exercises/first/components/Storyboard.vue
Labels: layout, refactoring

#76 Ajuste ranking geral
  src/commons/store/actions.js
  src/views/external/signup/Signup.vue
  src/views/internal/student/class/ranking/ClassRanking.vue
  src/views/internal/student/exercises/first/ExerciseFirst.vue
  src/views/internal/teacher/class/detail/ClassRanking.vue
Labels: refactoring

#77 Seleção de desafios por parte do professor
  src/commons/components/teacher/BottomNavigation.vue
  src/commons/constants/action-types.js
  src/commons/store/actions.js
  src/commons/store/mutations.js
  src/globals/router/index.js
  src/globals/router/routes/exercises.js
  src/globals/router/routes/student.js
  src/globals/router/routes/teacher.js
  src/views/internal/exercises/first/ExerciseFirst.vue
  src/views/internal/exercises/first/components/Feedback.vue
  src/views/internal/exercises/first/components/Storyboard.vue
  src/views/internal/student/class/exercises/ClassExercises.vue
  src/views/internal/student/class/exercises/components/ClassExercisesCard.vue
  src/views/internal/teacher/class/add/ClassAdd.vue
  src/views/internal/teacher/class/add/components/ClassFormActions.vue
  src/views/internal/teacher/class/add/components/ClassFormInputs.vue
  src/views/internal/teacher/class/commons/ClassName.vue
  src/views/internal/teacher/class/detail/ClassView.vue
  src/views/internal/teacher/class/detail/components/ClassQrCodeView.vue
  src/views/internal/teacher/class/detail/components/ClassRoomStudentCard.vue
  src/views/internal/teacher/class/detail/components/ClassStudentsView.vue
  src/views/internal/teacher/class/exercises/ClassExercises.vue
  src/views/internal/teacher/class/exercises/components/ClassExercisesCard.vue
  src/views/internal/teacher/class/ranking/ClassRanking.vue
  src/views/internal/teacher/class/ranking/components/ClassRankingChallengeSelect.vue
Labels: feature, layout, refactoring
