Repository developers-pantaneiros/game, pull requests merged in 2020-03, with the labels that each got.

#23 Implementar API de áudio
  src/views/internal/student/class/add/ClassAdd.vue
  src/views/internal/student/class/exercicies/ClassExercicies.vue
  src/views/internal/teacher/class/search/ClassSearch.vue
Labels: feature

#27 Adicionei uma nova biblioteca para os alertas
  package-lock.json
  package.json
  src/assets/scss/components/_alert.scss
  src/assets/scss/main.scss
  src/commons/components/Alert.vue
  src/main.js
  src/views/external/signin/Signin.vue
  src/views/external/signup/Signup.vue
  src/views/internal/student/class/add/ClassAdd.vue
  src/views/internal/teacher/class/detail/ClassAdd.vue
Labels: bug, warning

#31 Botao adicionar quebrado professor
  src/views/internal/student/class/search/ClassSearch.vue
  src/views/internal/teacher/class/search/ClassSearch.vue
Labels: bug, warning

#32 Drag and drop and layout changes
  package-lock.json
  package.json
  public/index.html
  src/assets/images/ice.png
  src/assets/images/rain.png
  src/assets/images/water.png
  src/assets/scss/base/_typography.scss
  src/assets/scss/base/_utilities.scss
  src/assets/scss/components/_container.scss
  src/assets/scss/components/_draggable-list.scss
  src/assets/scss/components/_exercise-card.scss
  src/assets/scss/main.scss
  src/commons/components/Alert.vue
  src/commons/components/student/BottomNavigation.vue
  src/commons/constants/mutation-types.js
  src/commons/store/mutations.js
  src/commons/store/state.js
  src/globals/router/routes/student.js
  src/globals/utils/shuffle.js
  src/views/external/signin/Signin.vue
  src/views/external/signin/components/SigninActions.vue
  src/views/external/signin/components/SigninEmailInput.vue
  src/views/external/signin/components/SigninInputs.vue
  src/views/external/signin/components/SigninPasswordInput.vue
  src/views/external/signup/Signup.vue
  src/views/external/signup/components/SignupEmailInput.vue
  src/views/external/signup/components/SignupInputs.vue
  src/views/external/signup/components/SignupNameInput.vue
  src/views/external/signup/components/SignupPasswordInput.vue
  src/views/external/signup/components/SignupRoleSelect.vue
  src/views/internal/student/class/classroom/ClassRoom.vue
  src/views/internal/student/class/exercises/ClassExercises.vue
  src/views/internal/student/class/exercises/components/ClassExercisesCard.vue
  src/views/internal/student/class/ranking/ClassRanking.vue
  src/views/internal/student/class/search/ClassSearch.vue
  src/views/internal/student/exercises/first/ExerciseFirst.vue
  src/views/internal/student/exercises/first/components/Feedback.vue
  src/views/internal/teacher/class/detail/ClassView.vue
  src/views/internal/teacher/class/search/ClassSearch.vue
Labels: bug, feature, layout, technical

#34 Visualizar pontuação de cada desafio
  src/commons/constants/action-types.js
  src/commons/store/actions.js
  src/globals/router/routes/student.js
  src/views/external/signin/Signin.vue
  src/views/internal/student/class/ranking/ClassRanking.vue
  src/views/internal/student/exercises/first/ExerciseFirst.vue
Labels: change, feature, layout

#35 Implementar função de SignOut da conta
  src/assets/scss/components/_float-button.scss
  src/commons/components/student/BottomNavigation.vue
  src/commons/constants/action-types.js
  src/commons/store/actions.js
  src/views/internal/student/class/search/ClassSearch.vue
  src/views/internal/student/class/search/components/ClassSearchAction.vue
  src/views/internal/student/class/search/components/ClassSearchSignOut.vue
  src/views/internal/teacher/class/detail/ClassView.vue
  src/views/internal/teacher/class/search/ClassSearch.vue
  src/views/internal/teacher/class/search/components/ClassSearchAction.vue
  src/views/internal/teacher/class/search/components/ClassSearchSignOut.vue
Labels: feature, layout

#36 Melhorias no layout e navegação
  src/commons/components/AudioButton.vue
  src/commons/components/student/BottomNavigation.vue
  src/views/external/signin/components/SigninActions.vue
  src/views/internal/student/class/add/ClassAdd.vue
  src/views/internal/student/class/add/components/ClassFormCode.vue
  src/views/internal/student/class/exercises/ClassExercises.vue
  src/views/internal/student/class/ranking/ClassRanking.vue
  src/views/internal/student/class/search/ClassSearch.vue
  src/views/internal/teacher/class/search/ClassSearch.vue
Labels: layout

#39 Refatorei o texto das mensagens de erro e sucesso
  src/views/external/reset/ResetPassword.vue
Labels: refactoring

#41 Redefinicao inscricao em uma turma
  src/globals/router/routes/student.js
  src/views/internal/student/class/add/AbstractClassAdd.vue
  src/views/internal/student/class/add/ClassAdd.vue
  src/views/internal/student/class/add/ClassAddCodeReader.vue
  src/views/internal/student/class/add/components/ClassFormActions.vue
  src/views/internal/student/class/add/components/ClassFormCodeReader.vue
  src/views/internal/student/class/add/components/ClassFormInputs.vue
Labels: change, refactoring
